# Your Wi-Fi SSID and password
wifi_ssid: "Your wi-fi"
wifi_password: "Your wi-fi password"

# Network settings
gateway_address: 192.168.0.1
subnet_address: 255.255.255.0
dns_address: 192.168.0.1

# Device Webserver
web_server_user: "admin"
web_server_password: "web_server_password"

# Home Assistant Api
api_password: "api_password"
api_encryption_key: "api_encryption_key"

# OTA
ota_password: "ota_password"

# MQTT
mqtt_ip: 192.168.0.0
mqtt_user: mqtt
mqtt_password: mqtt_password